name: github pages -- fimreal.github.io

on:
  push:
    branches:
      - src  # Set a branch to deploy
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: install hugo theme
        run: git clone https://github.com/olOwOlo/hugo-theme-even themes/even && cat themes/_variables.scss > themes/even/assets/sass/_variables.scss

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}     # see https://github.com/marketplace/actions/github-pages-action#github-actions-for-github-pages
          publish_dir: ./public
          cname: blog.epurs.com
          keep_files: false
