name: github pages -- fimreal.github.io

on:
  push:
    branches:
      - src  # Set a branch to deploy
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: install hugo theme
        run: git clone https://github.com/olOwOlo/hugo-theme-even themes/even
      - name: install hugo theme - change theme color
        run: cat themes/_variables.scss > themes/even/assets/sass/_variables.scss
      - name: install hugo theme - add text-shadow
        run: |
          sed -i '10a\  text-shadow: 0 1px 2px rgba(0,0,0,0.2);' themes/even/assets/sass/_base.scss

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/src'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}     # see https://github.com/marketplace/actions/github-pages-action#github-actions-for-github-pages
          publish_dir: ./public
          cname: blog.epurs.com
          keep_files: false
          publish_branch: master

      - name: for qcloud-webify
        run: |
          sed -i '/.Site.Copyright/ a<a href="https://webify.cloudbase.net/"> 🚀 Powered by CloudBase Webify</a>' themes/even/layouts/partials/footer.html
      - name: beian
        run: |
          sed -i '/.Site.Copyright/ a<a class="theme-link" href="http://beian.miit.gov.cn">京ICP备18059304号-1</a>' themes/even/layouts/partials/footer.html
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/src'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}     # see https://github.com/marketplace/actions/github-pages-action#github-actions-for-github-pages
          publish_dir: ./public
        # cname: www.epurs.com
          keep_files: false
          publish_branch: qcloud-webify

